### ISSUE TITLE
Attaching files to tasks

### ISSUE THREAD

**Issue by megamatman** [programster/SCRUMptious#4]
Hi,

Although it appears that I'm able to attach files to Tasks, the files themselves are inaccessible.

E.g.

1) Attached file "Test.csv" to a task - file seemed to attach OK.

2) Clicked on download link under 'Files in this Task'.

3) Redirected to:
http://XXXX/easycases/downloadfiles/Test.csv
which reports:

```
Oops! File not found.
File may be deleted or make sure you specified correct file name.
```

4) Attempting to upload "Test.csv" again results in "Test(1).csv" being created, which suggests the original "Test.csv" already exists.  Unfortunately "Test(1).csv" is equally inaccessible.

As my only exposure to Orangescrum is as a user of this (most excellent) Docker container, I'm not ruling out user error here....

Any guidance would be greatly appreciated.

Thanks

**Comment by programster** [comment]
Thanks for alerting me to this issue. I'll dig into it when I'm not working and get back to you.

**Comment by programster** [comment]
Hey @megamatman sorry for not getting back to you sooner. I just did a fresh install and am unable to reproduce the issue.

Please could you let me know:
- if you installed from a release or from source.
- what distribution did you use? (ubuntu 14.04/debian 8/centos 7 etc). 
- is there a `data` folder in your home directory with the following sub path `data/app/files/case_files`. In that folder  should be any files you attached to tasks. If you do have that path, please check the permissions. The data folder should be owned by your user, but the app folder and everything below it should be owned by www-data (the docker application should have done this for you).
