### ISSUE TITLE
A question

### ISSUE THREAD

**Issue by jwk-pl** [programster/SCRUMptious#5]
Dear Programster,
Is this project still alive?
I am asking it in the issues tab as I do not know how else to ask.

**Comment by programster** [comment]
Sorry for the late response. The project is not alive. I put in the initial effort (wanting to dockerize the project etc) thinking Orangescrum would continue to get updates, and that perhaps might merge mine. It became clear over time to me that 

* I would want to refactor almost the entire codebase if I was going to continue working with it.
* Orangescrum didn't seem to be updating the main project I forked from or addressing the issues that were raised there.

Perhaps things have changed as this was so long ago, but I think it would be easier to start from scratch.
